### ISSUE TITLE
Support for YAML like formatting

### ISSUE THREAD

**Issue by ad-si** [informatikr/aeson-pretty#32]
instead of

```json
{
    "name": "John Doe",
    "country": "Germany",
    "favorite_color": "green"
}
```
format it as

```yaml
name: John Doe
country: Germany
favorite_color: green
```
